import smtplib
import markdown
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime


def _markdown_to_html(md_text: str) -> str:
    """Wraps the digest markdown in a readable HTML email body."""
    body_html = markdown.markdown(md_text, extensions=["extra"])
    return f"""
    <html>
    <head>
      <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                max-width: 700px; margin: 40px auto; color: #1a1a1a; line-height: 1.6; }}
        h2   {{ color: #0d0d0d; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; }}
        h3   {{ color: #333; margin-top: 28px; }}
        ul   {{ padding-left: 20px; }}
        li   {{ margin-bottom: 6px; }}
        blockquote {{ border-left: 4px solid #0066cc; padding-left: 12px;
                      color: #444; font-style: italic; }}
        a    {{ color: #0066cc; }}
        hr   {{ border: none; border-top: 1px solid #e0e0e0; margin: 24px 0; }}
        .footer {{ font-size: 12px; color: #999; margin-top: 40px; }}
      </style>
    </head>
    <body>
      {body_html}
      <p class="footer">Generated by your Instagram AI Agent • {datetime.now().strftime("%Y-%m-%d %H:%M")}</p>
    </body>
    </html>
    """


def send_digest(digest_text: str, config: dict, gmail_app_password: str) -> None:
    """
    Sends the digest as an HTML email via Gmail SMTP.
    `config` should be the 'email' section of config.json.
    """
    email_cfg = config["email"]
    sender = email_cfg["from"]
    recipient = email_cfg["to"]
    subject = email_cfg["subject"]

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = recipient

    # Plain text fallback
    msg.attach(MIMEText(digest_text, "plain"))
    # Rich HTML version
    msg.attach(MIMEText(_markdown_to_html(digest_text), "html"))

    print(f"[emailer] Connecting to {email_cfg['smtp_server']}:465 ...")
    with smtplib.SMTP_SSL(email_cfg["smtp_server"], 465) as server:
        server.login(sender, gmail_app_password)
        server.sendmail(sender, recipient, msg.as_string())

    print(f"[emailer] Digest sent to {recipient}.")
